repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.5
    hooks:
      - id: ruff-check
      - id: ruff-format
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.28.0
    hooks:
      - id: gitleaks
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: venv/Scripts/python.exe -m pytest -q
        language: system
        pass_filenames: false
