"""add order idempotency

Revision ID: 18224caf490c
Revises: 47a4af572bec
Create Date: 2026-08-31 12:49:39.323770

"""
# ruff: noqa: I001
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18224caf490c'
down_revision: str | Sequence[str] | None = '47a4af572bec'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idempotency_key', sa.String(length=128), nullable=False))
        batch_op.create_unique_constraint('uq_orders_idempotency_key', ['idempotency_key'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint('uq_orders_idempotency_key', type_='unique')
        batch_op.drop_column('idempotency_key')

    # ### end Alembic commands ###
