"""add milestone awards

Revision ID: 18b20bca7946
Revises: 18224caf490c
Create Date: 2026-08-31 15:44:55.939452

"""
# ruff: noqa: I001
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import src.models.base


# revision identifiers, used by Alembic.
revision: str = '18b20bca7946'
down_revision: str | Sequence[str] | None = '18224caf490c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('milestone_awards',
    sa.Column('milestone_id', src.models.base.GUID(length=36), nullable=False),
    sa.Column('user_id', src.models.base.GUID(length=36), nullable=False),
    sa.Column('idempotency_key', sa.String(length=160), nullable=False),
    sa.Column('awarded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', src.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key'),
    sa.UniqueConstraint('milestone_id', 'user_id', name='uq_milestone_award_user')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('milestone_awards')
    # ### end Alembic commands ###
