"""add notification preferences

Revision ID: 66fb987e6019
Revises: 18b20bca7946
Create Date: 2026-08-31 16:10:34.210382

"""
# ruff: noqa: I001
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import src.models.base


# revision identifiers, used by Alembic.
revision: str = '66fb987e6019'
down_revision: str | Sequence[str] | None = '18b20bca7946'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_preferences',
    sa.Column('user_id', src.models.base.GUID(length=36), nullable=False),
    sa.Column('in_app_enabled', sa.Boolean(), nullable=False),
    sa.Column('email_enabled', sa.Boolean(), nullable=False),
    sa.Column('push_enabled', sa.Boolean(), nullable=False),
    sa.Column('muted_types', sa.JSON(), nullable=False),
    sa.Column('id', src.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_notification_preference_user')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification_preferences')
    # ### end Alembic commands ###
