"""initial schema

Revision ID: ac3fcf2d48cf
Revises: 
Create Date: 2026-08-31 11:21:23.949288

"""
# ruff: noqa: I001
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
import src.models.base


# revision identifiers, used by Alembic.
revision: str = 'ac3fcf2d48cf'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('PARTICIPANT', 'ORGANIZER', 'COMMUNITY_ADMIN', 'SUPER_ADMIN', name='platformrole', native_enum=False, length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', src.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index('ix_users_role_active', ['role', 'is_active'], unique=False)

    op.create_table('venues',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('region', sa.String(length=120), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('id', src.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('venues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_venues_city'), ['city'], unique=False)

    op.create_table('notifications',
    sa.Column('user_id', src.models.base.GUID(length=36), nullable=False),
    sa.Column('notification_type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', src.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('ix_notifications_user_read', ['user_id', 'read_at'], unique=False)

    op.create_table('organizations',
    sa.Column('owner_id', src.models.base.GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.String(length=2048), nullable=True),
    sa.Column('website_url', sa.String(length=2048), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', src.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizations_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_organizations_slug'), ['slug'], unique=True)

    op.create_table('profiles',
    sa.Column('user_id', src.models.base.GUID(length=36), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('photo_url', sa.String(length=2048), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('interests', sa.JSON(), nullable=False),
    sa.Column('skills', sa.JSON(), nullable=False),
    sa.Column('visibility', sa.Enum('PUBLIC', 'MEMBERS', 'PRIVATE', name='profilevisibility', native_enum=False, length=16), nullable=False),
    sa.Column('id', src.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_profiles_username'), ['username'], unique=True)

    op.create_table('communities',
    sa.Column('organization_id', src.models.base.GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.String(length=2048), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', src.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('communities', schema=None) as batch_op:
        batch_op.create_index('ix_communities_org_active', ['organization_id', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_communities_slug'), ['slug'], unique=True)

    op.create_table('achievement_rules',
    sa.Column('community_id', src.models.base.GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('condition_tree', sa.JSON(), nullable=False),
    sa.Column('reward_definition', sa.JSON(), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', src.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('community_id', 'slug', name='uq_achievement_rule_slug')
    )
    op.create_table('audit_logs',
    sa.Column('actor_id', src.models.base.GUID(length=36), nullable=True),
    sa.Column('community_id', src.models.base.GUID(length=36), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=80), nullable=False),
    sa.Column('target_id', src.models.base.GUID(length=36), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', src.models.base.GUID(length=36), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index('ix_audit_target', ['target_type', 'target_id'], unique=False)

    op.create_table('badges',
    sa.Column('community_id', src.models.base.GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon_url', sa.String(length=2048), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('requirements', sa.JSON(), nullable=False),
    sa.Column('reward_points', sa.Integer(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', src.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('community_id', 'slug', name='uq_badge_community_slug')
    )
    op.create_table('contributions',
    sa.Column('community_id', src.models.base.GUID(length=36), nullable=False),
    sa.Column('contributor_id', src.models.base.GUID(length=36), nullable=False),
    sa.Column('contribution_type', sa.Enum('MONETARY', 'EQUIPMENT', 'MATERIALS', 'VOLUNTEER_TIME', 'SERVICES', 'RESOURCES', name='contributiontype', native_enum=False, length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('reference', sa.String(length=128), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'VERIFIED', 'REJECTED', name='activitystatus', native_enum=False, length=16), nullable=False),
    sa.Column('verified_by_id', src.models.base.GUID(length=36), nullable=True),
    sa.Column('id', src.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contributor_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['verified_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contributions', schema=None) as batch_op:
        batch_op.create_index('ix_contributions_community_status', ['community_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_contributions_reference'), ['reference'], unique=False)

    op.create_table('events',
    sa.Column('community_id', src.models.base.GUID(length=36), nullable=False),
    sa.Column('organizer_id', src.models.base.GUID(length=36), nullable=False),
    sa.Column('venue_id', src.models.base.GUID(length=36), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('cover_image_url', sa.String(length=2048), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('contact_email', sa.String(length=320), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('location_type', sa.Enum('PHYSICAL', 'ONLINE', 'HYBRID', name='locationtype', native_enum=False, length=16), nullable=False),
    sa.Column('online_url', sa.String(length=2048), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'CANCELLED', 'COMPLETED', name='eventstatus', native_enum=False, length=16), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('geofence_enabled', sa.Boolean(), nullable=False),
    sa.Column('geofence_radius_meters', sa.Integer(), nullable=True),
    sa.Column('check_in_opens_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('check_in_closes_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('peer_confirmation_enabled', sa.Boolean(), nullable=False),
    sa.Column('confirmations_required', sa.Integer(), nullable=False),
    sa.Column('organizer_verification_enabled', sa.Boolean(), nullable=False),
    sa.Column('qr_attendance_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', src.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organizer_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_category'), ['category'], unique=False)
        batch_op.create_index('ix_events_community_status', ['community_id', 'status'], unique=False)
        batch_op.create_index('ix_events_discovery', ['status', 'starts_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_organizer_id'), ['organizer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_slug'), ['slug'], unique=True)

    op.create_table('leaderboards',
    sa.Column('community_id', src.models.base.GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('metric', sa.String(length=64), nullable=False),
    sa.Column('period', sa.String(length=32), nullable=False),
    sa.Column('max_entries', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', src.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('community_id', 'slug', name='uq_leaderboard_community_slug')
    )
    op.create_table('memberships',
    sa.Column('community_id', src.models.base.GUID(length=36), nullable=False),
    sa.Column('user_id', src.models.base.GUID(length=36), nullable=False),
    sa.Column('role', sa.Enum('MEMBER', 'ORGANIZER', 'ADMIN', name='membershiprole', native_enum=False, length=16), nullable=False),
    sa.Column('status', sa.Enum('INVITED', 'ACTIVE', 'SUSPENDED', 'LEFT', name='membershipstatus', native_enum=False, length=16), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', src.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('community_id', 'user_id', name='uq_membership_community_user')
    )
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.create_index('ix_memberships_user_status', ['user_id', 'status'], unique=False)

    op.create_table('milestones',
    sa.Column('community_id', src.models.base.GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon_url', sa.String(length=2048), nullable=True),
    sa.Column('reward_points', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', src.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('community_id', 'slug', name='uq_milestone_community_slug')
    )
    op.create_table('ranks',
    sa.Column('community_id', src.models.base.GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon_url', sa.String(length=2048), nullable=True),
    sa.Column('minimum_points', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', src.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('community_id', 'slug', name='uq_rank_community_slug')
    )
    op.create_table('activities',
    sa.Column('community_id', src.models.base.GUID(length=36), nullable=False),
    sa.Column('user_id', src.models.base.GUID(length=36), nullable=False),
    sa.Column('event_id', src.models.base.GUID(length=36), nullable=True),
    sa.Column('activity_type', sa.String(length=80), nullable=False),
    sa.Column('dimension', sa.Enum('PARTICIPATION', 'EXECUTION', 'CONTRIBUTION', 'SERVICE', 'LEADERSHIP', name='engagementdimension', native_enum=False, length=16), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'VERIFIED', 'REJECTED', name='activitystatus', native_enum=False, length=16), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified_by_id', src.models.base.GUID(length=36), nullable=True),
    sa.Column('id', src.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.create_index('ix_activities_community_dimension', ['community_id', 'dimension'], unique=False)

    op.create_table('badge_awards',
    sa.Column('badge_id', src.models.base.GUID(length=36), nullable=False),
    sa.Column('user_id', src.models.base.GUID(length=36), nullable=False),
    sa.Column('idempotency_key', sa.String(length=160), nullable=False),
    sa.Column('awarded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('awarded_by_id', src.models.base.GUID(length=36), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoke_reason', sa.Text(), nullable=True),
    sa.Column('id', src.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['awarded_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['badge_id'], ['badges.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('badge_id', 'user_id', name='uq_badge_award_user'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_table('event_staff',
    sa.Column('event_id', src.models.base.GUID(length=36), nullable=False),
    sa.Column('user_id', src.models.base.GUID(length=36), nullable=False),
    sa.Column('role', sa.Enum('MANAGER', 'CHECK_IN', 'TICKET_VALIDATOR', 'ATTENDANCE_VERIFIER', name='eventstaffrole', native_enum=False, length=24), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', src.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'user_id', name='uq_event_staff_event_user')
    )
    with op.batch_alter_table('event_staff', schema=None) as batch_op:
        batch_op.create_index('ix_event_staff_user_active', ['user_id', 'is_active'], unique=False)

    op.create_table('milestone_requirements',
    sa.Column('milestone_id', src.models.base.GUID(length=36), nullable=False),
    sa.Column('metric', sa.String(length=80), nullable=False),
    sa.Column('operator', sa.String(length=16), nullable=False),
    sa.Column('threshold', sa.Integer(), nullable=False),
    sa.Column('id', src.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('milestone_id', 'metric', name='uq_milestone_requirement_metric')
    )
    op.create_table('orders',
    sa.Column('reference', sa.String(length=64), nullable=False),
    sa.Column('user_id', src.models.base.GUID(length=36), nullable=False),
    sa.Column('event_id', src.models.base.GUID(length=36), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'CANCELLED', 'REFUNDED', 'EXPIRED', name='orderstatus', native_enum=False, length=16), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', src.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_reference'), ['reference'], unique=True)
        batch_op.create_index('ix_orders_user_status', ['user_id', 'status'], unique=False)

    op.create_table('peer_confirmations',
    sa.Column('event_id', src.models.base.GUID(length=36), nullable=False),
    sa.Column('confirmer_id', src.models.base.GUID(length=36), nullable=False),
    sa.Column('subject_id', src.models.base.GUID(length=36), nullable=False),
    sa.Column('decision', sa.Enum('CONFIRMED', 'CANNOT_CONFIRM', name='peerconfirmationdecision', native_enum=False, length=20), nullable=False),
    sa.Column('suspicious', sa.Boolean(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', src.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['confirmer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'confirmer_id', 'subject_id', name='uq_peer_confirmation_pair')
    )
    with op.batch_alter_table('peer_confirmations', schema=None) as batch_op:
        batch_op.create_index('ix_peer_confirmations_subject_decision', ['subject_id', 'decision'], unique=False)

    op.create_table('rank_requirements',
    sa.Column('rank_id', src.models.base.GUID(length=36), nullable=False),
    sa.Column('requirement_type', sa.String(length=40), nullable=False),
    sa.Column('reference_id', src.models.base.GUID(length=36), nullable=True),
    sa.Column('threshold', sa.Integer(), nullable=False),
    sa.Column('id', src.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['rank_id'], ['ranks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rank_id', 'requirement_type', 'reference_id', name='uq_rank_requirement')
    )
    op.create_table('tasks',
    sa.Column('community_id', src.models.base.GUID(length=36), nullable=False),
    sa.Column('event_id', src.models.base.GUID(length=36), nullable=True),
    sa.Column('created_by_id', src.models.base.GUID(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('priority', sa.Enum('LOW', 'NORMAL', 'HIGH', 'URGENT', name='taskpriority', native_enum=False, length=16), nullable=False),
    sa.Column('impact_point_reward', sa.Integer(), nullable=False),
    sa.Column('verification_required', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', src.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index('ix_tasks_community_due', ['community_id', 'due_at'], unique=False)

    op.create_table('ticket_types',
    sa.Column('event_id', src.models.base.GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('sales_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sales_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('visibility', sa.Enum('PUBLIC', 'HIDDEN', 'INVITE_ONLY', name='ticketvisibility', native_enum=False, length=16), nullable=False),
    sa.Column('max_per_user', sa.Integer(), nullable=False),
    sa.Column('id', src.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('max_per_user > 0', name='ck_ticket_type_max_per_user_positive'),
    sa.CheckConstraint('price >= 0', name='ck_ticket_type_price_nonnegative'),
    sa.CheckConstraint('quantity >= 0', name='ck_ticket_type_quantity_nonnegative'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ticket_types', schema=None) as batch_op:
        batch_op.create_index('ix_ticket_types_event_sales', ['event_id', 'sales_start', 'sales_end'], unique=False)

    op.create_table('impact_transactions',
    sa.Column('idempotency_key', sa.String(length=160), nullable=False),
    sa.Column('user_id', src.models.base.GUID(length=36), nullable=False),
    sa.Column('community_id', src.models.base.GUID(length=36), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('source_id', src.models.base.GUID(length=36), nullable=True),
    sa.Column('event_id', src.models.base.GUID(length=36), nullable=True),
    sa.Column('task_id', src.models.base.GUID(length=36), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'POSTED', 'REVERSED', name='impacttransactionstatus', native_enum=False, length=16), nullable=False),
    sa.Column('reversed_transaction_id', src.models.base.GUID(length=36), nullable=True),
    sa.Column('id', src.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reversed_transaction_id'], ['impact_transactions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    with op.batch_alter_table('impact_transactions', schema=None) as batch_op:
        batch_op.create_index('ix_impact_community_created', ['community_id', 'created_at'], unique=False)
        batch_op.create_index('ix_impact_user_status', ['user_id', 'status'], unique=False)

    op.create_table('payments',
    sa.Column('order_id', src.models.base.GUID(length=36), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_reference', sa.String(length=128), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUCCESSFUL', 'FAILED', 'CANCELLED', 'REFUNDED', name='paymentstatus', native_enum=False, length=16), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refunded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('provider_metadata', sa.JSON(), nullable=False),
    sa.Column('id', src.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index('ix_payments_order_status', ['order_id', 'status'], unique=False)
        batch_op.create_index('ix_payments_provider_reference', ['provider', 'provider_reference'], unique=True)

    op.create_table('task_assignments',
    sa.Column('task_id', src.models.base.GUID(length=36), nullable=False),
    sa.Column('assignee_id', src.models.base.GUID(length=36), nullable=False),
    sa.Column('assigned_by_id', src.models.base.GUID(length=36), nullable=False),
    sa.Column('status', sa.Enum('ASSIGNED', 'ACCEPTED', 'IN_PROGRESS', 'SUBMITTED', 'VERIFIED', 'REJECTED', 'OVERDUE', name='taskassignmentstatus', native_enum=False, length=16), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_by_id', src.models.base.GUID(length=36), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('id', src.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'assignee_id', name='uq_task_assignment_assignee')
    )
    with op.batch_alter_table('task_assignments', schema=None) as batch_op:
        batch_op.create_index('ix_task_assignments_assignee_status', ['assignee_id', 'status'], unique=False)

    op.create_table('tickets',
    sa.Column('public_id', sa.String(length=32), nullable=False),
    sa.Column('qr_token', sa.String(length=128), nullable=False),
    sa.Column('event_id', src.models.base.GUID(length=36), nullable=False),
    sa.Column('ticket_type_id', src.models.base.GUID(length=36), nullable=False),
    sa.Column('attendee_id', src.models.base.GUID(length=36), nullable=False),
    sa.Column('order_id', src.models.base.GUID(length=36), nullable=True),
    sa.Column('status', sa.Enum('RESERVED', 'PENDING_PAYMENT', 'PAID', 'ACTIVE', 'USED', 'CANCELLED', 'REFUNDED', 'EXPIRED', name='ticketstatus', native_enum=False, length=24), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('validated_by_id', src.models.base.GUID(length=36), nullable=True),
    sa.Column('id', src.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attendee_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ticket_type_id'], ['ticket_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['validated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qr_token')
    )
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.create_index('ix_tickets_attendee_status', ['attendee_id', 'status'], unique=False)
        batch_op.create_index('ix_tickets_event_status', ['event_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_tickets_public_id'), ['public_id'], unique=True)

    op.create_table('attendances',
    sa.Column('event_id', src.models.base.GUID(length=36), nullable=False),
    sa.Column('user_id', src.models.base.GUID(length=36), nullable=False),
    sa.Column('ticket_id', src.models.base.GUID(length=36), nullable=True),
    sa.Column('status', sa.Enum('NOT_CHECKED_IN', 'CHECKED_IN', 'GPS_VERIFIED', 'QR_VERIFIED', 'PEER_VERIFIED', 'ORGANIZER_VERIFIED', 'REJECTED', name='attendancestatus', native_enum=False, length=24), nullable=False),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('flagged_for_review', sa.Boolean(), nullable=False),
    sa.Column('review_reason', sa.Text(), nullable=True),
    sa.Column('id', src.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'user_id', name='uq_attendance_event_user')
    )
    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.create_index('ix_attendances_event_status', ['event_id', 'status'], unique=False)

    op.create_table('task_submissions',
    sa.Column('assignment_id', src.models.base.GUID(length=36), nullable=False),
    sa.Column('evidence_text', sa.Text(), nullable=True),
    sa.Column('evidence_url', sa.String(length=2048), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', src.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['task_assignments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_submissions', schema=None) as batch_op:
        batch_op.create_index('ix_task_submissions_assignment_submitted', ['assignment_id', 'submitted_at'], unique=False)

    op.create_table('attendance_verifications',
    sa.Column('attendance_id', src.models.base.GUID(length=36), nullable=False),
    sa.Column('method', sa.Enum('GPS', 'QR', 'PEER', 'ORGANIZER', name='verificationmethod', native_enum=False, length=16), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verifier_id', src.models.base.GUID(length=36), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('accuracy_meters', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('id', src.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attendance_id'], ['attendances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verifier_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attendance_id', 'method', name='uq_attendance_verification_method')
    )
    with op.batch_alter_table('attendance_verifications', schema=None) as batch_op:
        batch_op.create_index('ix_attendance_verifications_attendance_valid', ['attendance_id', 'is_valid'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_verifications', schema=None) as batch_op:
        batch_op.drop_index('ix_attendance_verifications_attendance_valid')

    op.drop_table('attendance_verifications')
    with op.batch_alter_table('task_submissions', schema=None) as batch_op:
        batch_op.drop_index('ix_task_submissions_assignment_submitted')

    op.drop_table('task_submissions')
    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.drop_index('ix_attendances_event_status')

    op.drop_table('attendances')
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tickets_public_id'))
        batch_op.drop_index('ix_tickets_event_status')
        batch_op.drop_index('ix_tickets_attendee_status')

    op.drop_table('tickets')
    with op.batch_alter_table('task_assignments', schema=None) as batch_op:
        batch_op.drop_index('ix_task_assignments_assignee_status')

    op.drop_table('task_assignments')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index('ix_payments_provider_reference')
        batch_op.drop_index('ix_payments_order_status')

    op.drop_table('payments')
    with op.batch_alter_table('impact_transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_impact_user_status')
        batch_op.drop_index('ix_impact_community_created')

    op.drop_table('impact_transactions')
    with op.batch_alter_table('ticket_types', schema=None) as batch_op:
        batch_op.drop_index('ix_ticket_types_event_sales')

    op.drop_table('ticket_types')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index('ix_tasks_community_due')

    op.drop_table('tasks')
    op.drop_table('rank_requirements')
    with op.batch_alter_table('peer_confirmations', schema=None) as batch_op:
        batch_op.drop_index('ix_peer_confirmations_subject_decision')

    op.drop_table('peer_confirmations')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index('ix_orders_user_status')
        batch_op.drop_index(batch_op.f('ix_orders_reference'))

    op.drop_table('orders')
    op.drop_table('milestone_requirements')
    with op.batch_alter_table('event_staff', schema=None) as batch_op:
        batch_op.drop_index('ix_event_staff_user_active')

    op.drop_table('event_staff')
    op.drop_table('badge_awards')
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_index('ix_activities_community_dimension')

    op.drop_table('activities')
    op.drop_table('ranks')
    op.drop_table('milestones')
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.drop_index('ix_memberships_user_status')

    op.drop_table('memberships')
    op.drop_table('leaderboards')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_slug'))
        batch_op.drop_index(batch_op.f('ix_events_organizer_id'))
        batch_op.drop_index('ix_events_discovery')
        batch_op.drop_index('ix_events_community_status')
        batch_op.drop_index(batch_op.f('ix_events_category'))

    op.drop_table('events')
    with op.batch_alter_table('contributions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contributions_reference'))
        batch_op.drop_index('ix_contributions_community_status')

    op.drop_table('contributions')
    op.drop_table('badges')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_target')
        batch_op.drop_index(batch_op.f('ix_audit_logs_occurred_at'))

    op.drop_table('audit_logs')
    op.drop_table('achievement_rules')
    with op.batch_alter_table('communities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_communities_slug'))
        batch_op.drop_index('ix_communities_org_active')

    op.drop_table('communities')
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_profiles_username'))

    op.drop_table('profiles')
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_slug'))
        batch_op.drop_index(batch_op.f('ix_organizations_owner_id'))

    op.drop_table('organizations')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('ix_notifications_user_read')

    op.drop_table('notifications')
    with op.batch_alter_table('venues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_venues_city'))

    op.drop_table('venues')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_role_active')
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
