"""add configurable business rules

Revision ID: b614db69b5bd
Revises: ac3fcf2d48cf
Create Date: 2026-08-31 11:57:48.972599

"""
# ruff: noqa: I001
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import src.models.base


# revision identifiers, used by Alembic.
revision: str = 'b614db69b5bd'
down_revision: str | Sequence[str] | None = 'ac3fcf2d48cf'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_categories',
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', src.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('contribution_bands',
    sa.Column('community_id', src.models.base.GUID(length=36), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('minimum_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('maximum_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('per_user_period_cap', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', src.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('community_id', 'currency', 'minimum_amount', name='uq_contribution_band')
    )
    op.create_table('point_rules',
    sa.Column('community_id', src.models.base.GUID(length=36), nullable=True),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('max_awards_per_user', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', src.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('community_id', 'source_type', name='uq_point_rule_community_source')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('point_rules')
    op.drop_table('contribution_bands')
    op.drop_table('event_categories')
    # ### end Alembic commands ###
