const API_ORIGIN = (import.meta.env.VITE_API_ORIGIN || '').replace(/\/$/, '');
export const API_BASE = `${API_ORIGIN}/api/v1`;
export class ApiError extends Error { constructor(public readonly status: number, message: string, public readonly kind: 'auth' | 'forbidden' | 'server' | 'unexpected' | 'network') { super(message); } }
export function apiUrl(path: string): string { return `${API_BASE}/${path.replace(/^\//, '')}`; }
export function authHeaders(token?: string): HeadersInit { return token ? { Authorization: `Bearer ${token}` } : {}; }
async function responseMessage(response: Response, fallback: string): Promise<string> { const contentType = response.headers.get('content-type') || ''; if (contentType.includes('application/json')) { const body = await response.json().catch(() => null); if (typeof body?.detail === 'string') return body.detail; if (typeof body?.message === 'string') return body.message; } return fallback; }
export async function apiFetch(path: string, init: RequestInit = {}, token?: string): Promise<Response> { const headers = new Headers(init.headers); if (token && !headers.has('Authorization')) headers.set('Authorization', `Bearer ${token}`); return fetch(apiUrl(path), { ...init, headers }); }
async function refreshSession(): Promise<string | undefined> { const raw = sessionStorage.getItem('tickvendor.session'); if (!raw) return undefined; const current = JSON.parse(raw) as { refresh_token?: string }; if (!current.refresh_token) return undefined; const response = await fetch(apiUrl('auth/refresh'), { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ refresh_token: current.refresh_token }) }); if (!response.ok) return undefined; const next = await response.json(); sessionStorage.setItem('tickvendor.session', JSON.stringify(next)); return next.access_token as string; }
export async function apiJson<T>(path: string, init: RequestInit = {}, token?: string): Promise<T> { let response: Response; try { response = await apiFetch(path, init, token); } catch { throw new ApiError(0, 'Unable to reach TickVendor. Check your connection and try again.', 'network'); } if (response.status === 401 && token) { const refreshed = await refreshSession().catch(() => undefined); if (refreshed) return apiJson<T>(path, init, refreshed); } if (!response.ok) { const kind = response.status === 401 ? 'auth' : response.status === 403 ? 'forbidden' : response.status >= 500 ? 'server' : 'unexpected'; const fallback = kind === 'auth' ? 'Your session has expired. Please sign in again.' : kind === 'forbidden' ? 'You do not have access to this information.' : 'TickVendor could not load this information. Please try again.'; throw new ApiError(response.status, await responseMessage(response, fallback), kind); } const contentType = response.headers.get('content-type') || ''; if (!contentType.includes('application/json')) throw new ApiError(response.status, 'TickVendor returned an unexpected response. Please try again.', 'unexpected'); try { return await response.json() as T; } catch { throw new ApiError(response.status, 'TickVendor returned unreadable data. Please try again.', 'unexpected'); } }
