import { useState, type ReactNode } from 'react';

export interface BeforeInstallPromptEvent extends Event { prompt: () => Promise<void>; userChoice: Promise<{ outcome: 'accepted' | 'dismissed' }> }
type NavItem = { id: string; label: string; icon: string };
export type WorkspaceCommunity = { id: string; name: string; role: string; status: string };
export const participantNav: NavItem[] = [{ id: 'home', label: 'Home', icon: '⌂' }, { id: 'events', label: 'Discover', icon: '◎' }, { id: 'opportunities', label: 'Opportunities', icon: '◇' }, { id: 'tickets', label: 'My tickets', icon: '▤' }, { id: 'activity', label: 'Activity', icon: '◒' }, { id: 'achievements', label: 'Achievements', icon: '✦' }];
export const secondaryNav: NavItem[] = [{ id: 'tasks', label: 'Tasks', icon: '✓' }, { id: 'communities', label: 'Communities', icon: '♧' }, { id: 'notifications', label: 'Notifications', icon: '◌' }];
const managementGroups: { label: string; ids: string[] }[] = [
  { label: 'Overview', ids: ['organizer-dashboard'] },
  { label: 'Programs', ids: ['organizer-events', 'organizer-opportunities', 'organizer-tasks'] },
  { label: 'People & participation', ids: ['organizer-members', 'organizer-review', 'organizer-attendance'] },
  { label: 'Impact & recognition', ids: ['admin-leaderboards', 'admin-recognition', 'admin-adjustments'] },
  { label: 'Settings & insights', ids: ['admin-rules', 'admin-bands', 'admin-notifications', 'admin-analytics', 'admin-audit'] },
];
export function EmptyState({ title, description, action, onAction }: { title: string; description: string; action?: string; onAction?: () => void }) { return <div className="empty-state"><span className="empty-state-icon" aria-hidden="true">◈</span><h3>{title}</h3><p>{description}</p>{action && onAction && <button onClick={onAction}>{action}</button>}</div> }
export function AccountMenu({ user, installPrompt, onInstall, onSignOut, onProfile }: { user: { display_name: string; email: string; role: string }; installPrompt: BeforeInstallPromptEvent | null; onInstall: () => void; onSignOut: () => void; onProfile: () => void }) { return <details className="account-menu"><summary aria-label="Open account menu"><span className="avatar" aria-hidden="true">{user.display_name.slice(0, 1).toUpperCase()}</span><span className="account-name">{user.display_name}</span><span aria-hidden="true">⌄</span></summary><div className="account-popover"><strong>{user.display_name}</strong><small>{user.email}</small><small className="role-label">{user.role.replaceAll('_', ' ')}</small><button className="menu-action" onClick={onProfile}>Profile and settings</button>{installPrompt && <button className="menu-action" onClick={onInstall}>Install TickVendor</button>}<button className="menu-action danger" onClick={onSignOut}>Sign out</button></div></details> }

function WorkspaceSelector({ workspace, selectedCommunity, managedCommunities, onWorkspaceChange, mobile = false }: { workspace: 'participant' | 'management'; selectedCommunity?: WorkspaceCommunity; managedCommunities: WorkspaceCommunity[]; onWorkspaceChange: (workspace: 'participant' | 'management', communityId?: string) => void; mobile?: boolean }) {
  const value = workspace === 'management' && selectedCommunity ? selectedCommunity.id : 'participant';
  return <label className={`workspace-selector${mobile ? ' workspace-selector-mobile' : ''}`}><span className="workspace-selector-label">Workspace</span><select aria-label="Select workspace" value={value} onChange={event => event.target.value === 'participant' ? onWorkspaceChange('participant') : onWorkspaceChange('management', event.target.value)}><option value="participant">Personal · Participant workspace</option><optgroup label="Management">{managedCommunities.map(item => <option key={item.id} value={item.id}>{item.name} · Management workspace</option>)}</optgroup></select></label>;
}

export function AppShell({ children, user, view, setView, installPrompt, onInstall, onSignOut, onProfile, roleItems, workspace, selectedCommunity, managedCommunities, onWorkspaceChange }: { children: ReactNode; user: { display_name: string; email: string; role: string }; view: string; setView: (view: string) => void; installPrompt: BeforeInstallPromptEvent | null; onInstall: () => void; onSignOut: () => void; onProfile: () => void; roleItems: NavItem[]; workspace: 'participant' | 'management'; selectedCommunity?: WorkspaceCommunity; managedCommunities: WorkspaceCommunity[]; onWorkspaceChange: (workspace: 'participant' | 'management', communityId?: string) => void }) {
  const [moreOpen, setMoreOpen] = useState(false);
  const go = (id: string) => { const target = ({ home: 'home', activity: 'attendance', achievements: 'recognition' } as Record<string, string>)[id] || id; setView(target); setMoreOpen(false); };
  const isActive = (id: string) => view === (({ home: 'home', activity: 'attendance', achievements: 'recognition' } as Record<string, string>)[id] || id);
  const management = workspace === 'management' && Boolean(selectedCommunity);
  const workspaceLabel = management ? `${selectedCommunity?.name} · Management workspace` : 'Participant workspace';
  const availableItems = new Map(roleItems.map(item => [item.id, item]));
  return <div className="app-shell"><header className="app-header"><a className="brand" href="#home" onClick={() => go('home')}>TickVendor</a><div className="header-context"><span className="workspace-label">{workspaceLabel}</span><button className="notification-button" aria-label="Open notifications" onClick={() => go('notifications')}><span aria-hidden="true">◌</span></button><AccountMenu user={user} installPrompt={installPrompt} onInstall={onInstall} onSignOut={onSignOut} onProfile={onProfile} /></div></header><WorkspaceSelector workspace={workspace} selectedCommunity={selectedCommunity} managedCommunities={managedCommunities} onWorkspaceChange={onWorkspaceChange} mobile /><div className="app-layout"><aside className="sidebar" aria-label="Workspace navigation"><WorkspaceSelector workspace={workspace} selectedCommunity={selectedCommunity} managedCommunities={managedCommunities} onWorkspaceChange={onWorkspaceChange} /><nav><p className="sidebar-title">Workspace</p>{participantNav.map(item => <button key={item.id} className={isActive(item.id) ? 'active' : ''} onClick={() => go(item.id)}><span aria-hidden="true">{item.icon}</span>{item.label}</button>)}<p className="sidebar-title secondary-title">More</p>{secondaryNav.map(item => <button key={item.id} className={isActive(item.id) ? 'active' : ''} onClick={() => go(item.id)}><span aria-hidden="true">{item.icon}</span>{item.label}</button>)}{management && managementGroups.map(group => { const items = group.ids.map(id => availableItems.get(id)).filter((item): item is NavItem => Boolean(item)); return items.length ? <div key={group.label}><p className="sidebar-title secondary-title">{group.label}</p>{items.map(item => <button key={item.id} className={isActive(item.id) ? 'active' : ''} onClick={() => go(item.id)}><span aria-hidden="true">{item.icon}</span>{item.label}</button>)}</div> : null; })}</nav></aside><div className="app-main">{children}</div></div><nav className="mobile-bottom-nav" aria-label="Primary mobile navigation">{participantNav.map(item => <button key={item.id} className={isActive(item.id) ? 'active' : ''} onClick={() => go(item.id)}><span aria-hidden="true">{item.icon}</span><span>{item.label}</span></button>)}<button className={moreOpen ? 'active' : ''} onClick={() => setMoreOpen(!moreOpen)} aria-expanded={moreOpen}><span aria-hidden="true">•••</span><span>More</span></button></nav>{moreOpen && <div className="mobile-sheet-backdrop" onClick={() => setMoreOpen(false)}><section className="mobile-sheet" role="dialog" aria-modal="true" aria-labelledby="more-title" onClick={event => event.stopPropagation()}><div className="sheet-handle" aria-hidden="true" /><h2 id="more-title">More</h2>{[...secondaryNav, ...(management ? roleItems : [])].map(item => <button key={item.id} onClick={() => go(item.id)}><span aria-hidden="true">{item.icon}</span>{item.label}</button>)}<button onClick={() => { onProfile(); setMoreOpen(false); }}>Profile and settings</button></section></div>}</div>
}
