import { useState } from 'react';
import { apiJson } from './api';
import { TaskDialog } from './RevealFocus';
type Preview = { members: { user_id: string; email: string; name: string }[]; invalid: string[]; unresolved: string[]; count: number; selection_version: string };
export function BulkTaskAssignment({ token, task, onClose, onDone }: { token: string; task: { id: string; title: string }; onClose: () => void; onDone: (message: string) => void }) {
  const [search, setSearch] = useState(''); const [emails, setEmails] = useState(''); const [preview, setPreview] = useState<Preview | null>(null);
  const [selected, setSelected] = useState<string[]>([]); const [all, setAll] = useState(false); const [confirmed, setConfirmed] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const resolve = async (mode: 'search' | 'emails' | 'all') => { setBusy(true); setError(''); setConfirmed(false); setPreview(null); setSelected([]); setAll(mode === 'all'); try { setPreview(await apiJson<Preview>(`tasks/${task.id}/assignment-candidates`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(mode === 'emails' ? { emails } : mode === 'all' ? { all_members: true } : { search }) }, token)); } catch(e) { setError(e instanceof Error ? e.message : 'Unable to resolve members'); } finally { setBusy(false); } };
  const assign = async () => { setBusy(true); setError(''); try { const result = await apiJson<{ assigned: number; already_assigned: number }>(`tasks/${task.id}/assignments/bulk`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ selected_ids: selected, all_members: all, selection_version: all ? preview?.selection_version : undefined }) }, token); onDone(`${result.assigned} assigned; ${result.already_assigned} already assigned. Notifications queued for new assignments.`); onClose(); } catch(e) { setError(e instanceof Error ? e.message : 'Assignment failed'); } finally { setBusy(false); } };
  return <TaskDialog title={`Assign: ${task.title}`} onClose={() => { if (!busy) onClose(); }}><section className="panel" style={{ maxWidth: '42rem' }}><h2>Assign: {task.title}</h2><p>Only active eligible members of this task’s community can be matched. Existing assignments are retained.</p>
    <label>Search members by name or email<input value={search} onChange={e => setSearch(e.target.value)} /></label><button disabled={busy} onClick={() => resolve('search')}>Find members</button>
    <label>Paste emails (newline, comma, semicolon or space separated)<textarea maxLength={100000} value={emails} onChange={e => setEmails(e.target.value)} /></label><button disabled={busy || !emails.trim()} onClick={() => resolve('emails')}>Resolve emails</button>
    <button disabled={busy} onClick={() => resolve('all')}>Preview all eligible community members</button>{error && <p role="alert">{error}</p>}{busy && <p role="status">Working…</p>}
    {preview && <><p>{preview.count} eligible matches. Duplicate emails are combined.</p>{preview.invalid.length > 0 && <p>Invalid emails: {preview.invalid.join(', ')}</p>}{preview.unresolved.length > 0 && <p>Not matched to an eligible member in this community: {preview.unresolved.join(', ')}</p>}
      {!all && <><button onClick={() => setSelected(preview.members.map(m => m.user_id))}>Select All matched</button><button onClick={() => setSelected([])}>Clear selection</button></>}
      <div style={{ maxHeight: '16rem', overflowY: 'auto', overflowWrap: 'anywhere' }}>{preview.members.map(m => <label key={m.user_id}><input type="checkbox" checked={all || selected.includes(m.user_id)} disabled={busy || all} onChange={e => setSelected(v => e.target.checked ? [...v, m.user_id] : v.filter(id => id !== m.user_id))} />{m.name} — {m.email}</label>)}</div>
      {all && <label><input type="checkbox" checked={confirmed} onChange={e => setConfirmed(e.target.checked)} />I confirm assigning this task to all {preview.count} eligible members of this community, not all platform users.</label>}
      <button disabled={busy || (all ? !confirmed || !preview.count : !selected.length)} onClick={assign}>{all ? 'Assign to All eligible community members' : `Assign selected (${selected.length})`}</button></>}
    <button disabled={busy} onClick={onClose}>Close</button></section></TaskDialog>;
}
