import { useState } from 'react';
import { apiJson } from './api';
import { useDraftState } from './formRecovery';
import { TaskDialog } from './RevealFocus';
export function CreateCommunity({ token, onClose, onCreated }: { token: string; onClose: () => void; onCreated: () => void }) {
  const draft = useDraftState('community-create', { name: '', slug: '', description: '', is_public: true, membership_access: 'invite_only' });
  const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  return <TaskDialog title="Create community" onClose={onClose}><form className="panel" onSubmit={async e => { e.preventDefault(); setBusy(true); setError(''); try { await apiJson('communities', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(draft.value) }, token); await draft.clear(); onCreated(); onClose(); } catch(e) { setError(e instanceof Error ? e.message : 'Unable to create community'); } finally { setBusy(false); } }}><h2>Create community</h2><p>Existing community administrators and Super Admins may create communities. Creation grants an organizer membership; only a Super Admin can appoint a community administrator.</p>{error && <p role="alert">{error}</p>}{draft.error && <p role="alert">{draft.error}</p>}
    <label>Name<input required minLength={2} maxLength={160} value={draft.value.name} onChange={e => draft.set(v => ({ ...v, name: e.target.value }))} /></label><label>Unique slug<input required minLength={2} maxLength={100} pattern="[a-z0-9]+(-[a-z0-9]+)*" value={draft.value.slug} onChange={e => draft.set(v => ({ ...v, slug: e.target.value }))} /></label><label>Description<textarea maxLength={5000} value={draft.value.description} onChange={e => draft.set(v => ({ ...v, description: e.target.value }))} /></label><label><input type="checkbox" checked={draft.value.is_public} onChange={e => draft.set(v => ({ ...v, is_public: e.target.checked }))} />Publicly discoverable</label><label>Membership access<select value={draft.value.membership_access} onChange={e => draft.set(v => ({ ...v, membership_access: e.target.value }))}>{['invite_only','approval_required','open'].map(v => <option key={v}>{v}</option>)}</select></label>
    <button disabled={busy || !draft.ready}>{busy ? 'Creating…' : 'Create community'}</button><button type="button" disabled={busy} onClick={onClose}>Close and keep draft</button></form></TaskDialog>;
}
