import { useState } from 'react';
import { apiJson } from './api';
import { useDraftState } from './formRecovery';
import { TaskDialog } from './RevealFocus';
type OrganizationOption = { id: string; name: string };
export function CreateCommunity({ token, organizations, onClose, onCreated }: { token: string; organizations: OrganizationOption[]; onClose: () => void; onCreated: () => void }) {
  const draft = useDraftState('community-create', { name: '', slug: '', description: '', is_public: true, membership_access: 'invite_only', organization_id: '' });
  const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  return <TaskDialog title="Create or apply for a community" onClose={onClose}><form className="panel" onSubmit={async e => { e.preventDefault(); setBusy(true); setError(''); try { const submitter = (e.nativeEvent as SubmitEvent).submitter as HTMLButtonElement | null; const body = { ...draft.value, organization_id: draft.value.organization_id || null, submit_for_review: submitter?.value !== 'draft' }; await apiJson('communities', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }, token); await draft.clear(); onCreated(); onClose(); } catch(e) { setError(e instanceof Error ? e.message : 'Unable to create community'); } finally { setBusy(false); } }}><h2>Create or apply for a community</h2><p>A new independent organization requires Platform review. An active Community Admin may add a community directly only within an organization they already govern.</p>{error && <p role="alert">{error}</p>}{draft.error && <p role="alert">{draft.error}</p>}
    <label>Organization<select value={draft.value.organization_id} onChange={e => draft.set(v => ({ ...v, organization_id: e.target.value }))}><option value="">New independent organization — submit for review</option>{organizations.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>
    <label>Name<input required minLength={2} maxLength={160} value={draft.value.name} onChange={e => draft.set(v => ({ ...v, name: e.target.value }))} /></label><label>Unique slug<input required minLength={2} maxLength={100} pattern="[a-z0-9]+(-[a-z0-9]+)*" value={draft.value.slug} onChange={e => draft.set(v => ({ ...v, slug: e.target.value }))} /></label><label>Description<textarea maxLength={5000} value={draft.value.description} onChange={e => draft.set(v => ({ ...v, description: e.target.value }))} /></label><label><input type="checkbox" checked={draft.value.is_public} onChange={e => draft.set(v => ({ ...v, is_public: e.target.checked }))} />Publicly discoverable</label><label>Membership access<select value={draft.value.membership_access} onChange={e => draft.set(v => ({ ...v, membership_access: e.target.value }))}>{['invite_only','approval_required','open'].map(v => <option key={v}>{v}</option>)}</select></label>
    <button disabled={busy || !draft.ready}>{busy ? 'Submitting…' : draft.value.organization_id ? 'Create community' : 'Submit application'}</button>{!draft.value.organization_id && <button className="secondary" name="intent" value="draft" disabled={busy || !draft.ready}>Save server draft</button>}<button type="button" disabled={busy} onClick={onClose}>Close and keep draft</button></form></TaskDialog>;
}
