type Question = { id: string; prompt: string; kind: string; choices: string[]; required?: boolean };
export type LearningConfig = { assessment?: { questions: Question[]; passing_score: number; max_attempts: number }; checkpoints?: { items: { id: string; prompt: string; position: string }[]; max_attempts: number; minimum_correct?: number } };
export function LearningAnswers({ config, answers, onChange }: { config: LearningConfig; answers: Record<string, any>; onChange: (answers: Record<string, any>) => void }) {
  const set = (id: string, value: unknown) => onChange({ ...answers, [id]: value });
  return <section><h3>Task questions</h3>{config.checkpoints && <p>Checkpoint codes are evidence of attention, not proof of watching the entire video. Organizer review may also be required. Maximum attempts: {config.checkpoints.max_attempts}.</p>}
    {config.checkpoints?.items.map(q => <label key={q.id}>{q.position} — {q.prompt}<input maxLength={100} value={answers[q.id] || ''} onChange={e => set(q.id, e.target.value)} /></label>)}
    {config.assessment && <p>Maximum attempts: {config.assessment.max_attempts}. Surveys record completion, not a preferred opinion.</p>}
    {config.assessment?.questions.map(q => <fieldset key={q.id}><legend>{q.prompt}{q.required ? ' *' : ''}</legend>
      {['single', 'multiple'].includes(q.kind) ? q.choices.map((choice, i) => <label key={i}><input type={q.kind === 'single' ? 'radio' : 'checkbox'} name={q.id} checked={(answers[q.id] || []).includes(i)} onChange={e => set(q.id, q.kind === 'single' ? [i] : e.target.checked ? [...(answers[q.id] || []), i] : (answers[q.id] || []).filter((v: number) => v !== i))} />{choice}</label>) : q.kind === 'rating' ? <label>Rating (1–5)<select value={answers[q.id] || ''} onChange={e => set(q.id, Number(e.target.value))}><option value="">Choose</option>{[1,2,3,4,5].map(v => <option key={v}>{v}</option>)}</select></label> : <label>Your response<textarea maxLength={q.kind === 'short_text' ? 500 : 5000} value={answers[q.id] || ''} onChange={e => set(q.id, e.target.value)} /></label>}
    </fieldset>)}
  </section>;
}

export type BuilderData = { questions: { prompt: string; kind: string; choices: string; correct: string; required?: boolean }[]; checkpoints: { position: string; prompt: string; expected: string }[]; attempts: number; passing: number; minimum: number };
export const emptyLearning: BuilderData = { questions: [], checkpoints: [], attempts: 3, passing: 100, minimum: 0 };
export function buildLearning(kind: string, data: BuilderData) {
  if (kind === 'video' && data.checkpoints.length) return { checkpoints: { items: data.checkpoints.map((q, i) => ({ ...q, id: `c${i}` })), max_attempts: data.attempts, minimum_correct: data.minimum || null, case_sensitive: false } };
  if (['quiz', 'survey'].includes(kind) && data.questions.length) return { assessment: { questions: data.questions.map((q, i) => ({ id: `q${i}`, prompt: q.prompt, kind: q.kind, choices: ['single','multiple'].includes(q.kind) ? q.choices.split('\n').filter(Boolean) : [], ...(kind === 'quiz' ? { correct: q.correct.split(',').map(v => Number(v.trim()) - 1) } : {}), required: q.required !== false })), passing_score: data.passing, max_attempts: data.attempts } };
  return {};
}
export function LearningBuilder({ kind, data, onChange }: { kind: string; data: BuilderData; onChange: (value: BuilderData) => void }) {
  if (!['quiz','survey','video'].includes(kind)) return null;
  return <section className="panel"><h3>{kind === 'video' ? 'Attention checkpoints' : 'Questions'}</h3><p>{kind === 'video' ? 'Place the expected codes in your video. Codes can be shared and are not guaranteed watch verification. Leave empty for a normal video task.' : kind === 'quiz' ? 'Objective choice grading only. Correct choice numbers start at 1.' : 'Survey completion is never graded by opinion. Leave empty to retain an external survey link.'}</p>
    <label>Maximum attempts<input type="number" min={1} max={20} value={data.attempts} onChange={e => onChange({ ...data, attempts: Number(e.target.value) })} /></label>
    {kind === 'quiz' && <label>Passing percentage<input type="number" min={0} max={100} value={data.passing} onChange={e => onChange({ ...data, passing: Number(e.target.value) })} /></label>}
    {kind === 'video' ? <><label>Required correct checkpoints (0 means all)<input type="number" min={0} max={data.checkpoints.length} value={data.minimum} onChange={e => onChange({ ...data, minimum: Number(e.target.value) })} /></label>{data.checkpoints.map((q, i) => <fieldset key={i}><legend>Checkpoint {i+1}</legend>{(['position','prompt','expected'] as const).map(field => <label key={field}>{field}<input required value={q[field]} onChange={e => onChange({ ...data, checkpoints: data.checkpoints.map((item, n) => n === i ? { ...item, [field]: e.target.value } : item) })} /></label>)}<button type="button" onClick={() => onChange({ ...data, checkpoints: data.checkpoints.filter((_, n) => n !== i) })}>Remove checkpoint</button></fieldset>)}<button type="button" disabled={data.checkpoints.length >= 20} onClick={() => onChange({ ...data, checkpoints: [...data.checkpoints, { position: '', prompt: '', expected: '' }] })}>Add checkpoint</button></> : <>{data.questions.map((q,i) => <fieldset key={i}><legend>Question {i+1}</legend><label>Prompt<input required value={q.prompt} onChange={e => onChange({ ...data, questions: data.questions.map((item,n) => n === i ? { ...item, prompt: e.target.value } : item) })} /></label><label><input type="checkbox" checked={q.required !== false} onChange={e => onChange({ ...data, questions: data.questions.map((item,n) => n === i ? { ...item, required: e.target.checked } : item) })} />Required response</label><label>Type<select value={q.kind} onChange={e => onChange({ ...data, questions: data.questions.map((item,n) => n === i ? { ...item, kind: e.target.value } : item) })}>{(kind === 'quiz' ? ['single','multiple'] : ['single','multiple','rating','short_text','long_text']).map(v => <option key={v}>{v}</option>)}</select></label>{['single','multiple'].includes(q.kind) && <label>Choices (one per line)<textarea required value={q.choices} onChange={e => onChange({ ...data, questions: data.questions.map((item,n) => n === i ? { ...item, choices: e.target.value } : item) })} /></label>}{kind === 'quiz' && <label>Correct choice numbers, comma separated<input required value={q.correct} onChange={e => onChange({ ...data, questions: data.questions.map((item,n) => n === i ? { ...item, correct: e.target.value } : item) })} /></label>}<button type="button" onClick={() => onChange({ ...data, questions: data.questions.filter((_,n) => n !== i) })}>Remove question</button></fieldset>)}<button type="button" disabled={data.questions.length >= 30} onClick={() => onChange({ ...data, questions: [...data.questions, { prompt: '', kind: 'single', choices: '', correct: '' }] })}>Add question</button></>}
  </section>;
}
