import { useState } from 'react';

type Config = { qr_attendance_enabled: boolean; geofence_enabled: boolean; organizer_verification_enabled: boolean; peer_confirmation_enabled: boolean; geofence_radius_meters: number; max_peer_confirmations: number; confirmations_required: number; peer_selection_limit: number; required_verification_methods: string[] };
const initial: Config = { qr_attendance_enabled: true, geofence_enabled: false, organizer_verification_enabled: true, peer_confirmation_enabled: false, geofence_radius_meters: 100, max_peer_confirmations: 3, confirmations_required: 0, peer_selection_limit: 5, required_verification_methods: [] };
export function OrganizerAttendanceConfig({ token, communityId, eventId }: { token: string; communityId: string; eventId: string }) {
  const [config, setConfig] = useState(initial); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const toggle = (field: keyof Config) => setConfig(current => ({ ...current, [field]: !current[field] }));
  const save = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); setError(''); setMessage(''); try { const response = await fetch(`/api/v1/communities/${communityId}/events/${eventId}/attendance-config`, { method: 'PATCH', headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' }, body: JSON.stringify(config) }); const data = await response.json(); if (!response.ok) throw Error(data.detail || 'Unable to save attendance configuration'); setMessage('Attendance configuration saved.'); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to save attendance configuration'); } finally { setBusy(false); } };
  return <form className="panel" onSubmit={save}><h4>Attendance configuration</h4><label><input type="checkbox" checked={config.qr_attendance_enabled} onChange={() => toggle('qr_attendance_enabled')} /> QR verification</label><label><input type="checkbox" checked={config.geofence_enabled} onChange={() => toggle('geofence_enabled')} /> GPS/geofence</label><label><input type="checkbox" checked={config.organizer_verification_enabled} onChange={() => toggle('organizer_verification_enabled')} /> Organizer verification</label><label><input type="checkbox" checked={config.peer_confirmation_enabled} onChange={() => toggle('peer_confirmation_enabled')} /> Peer confirmation</label><label>Required methods<select multiple value={config.required_verification_methods} onChange={event => setConfig({ ...config, required_verification_methods: Array.from(event.target.selectedOptions, option => option.value) })}><option value="qr">QR</option><option value="gps">GPS</option><option value="peer">Peer</option><option value="organizer">Organizer</option></select></label><label>Required peer confirmations<input type="number" min="0" max="100" value={config.confirmations_required} onChange={event => setConfig({ ...config, confirmations_required: Number(event.target.value) })} /></label><label>Maximum peer confirmations<input type="number" min="1" max="100" value={config.max_peer_confirmations} onChange={event => setConfig({ ...config, max_peer_confirmations: Number(event.target.value) })} /></label><button disabled={busy}>{busy ? 'Saving…' : 'Save attendance settings'}</button>{message && <p role="status">{message}</p>}{error && <p role="alert" className="error">{error}</p>}</form>;
}
