/** Organization admin opportunity management UI. */
import { useEffect, useState } from 'react';
import { apiJson, ApiError } from './api';

type Opportunity = { id: string; title: string; description: string; activity_type: string; starts_at: string; ends_at: string; location?: string | null; status: string };
export function OrganizerOpportunities({ token, communityId }: { token: string; communityId?: string }) {
  const [community, setCommunity] = useState(''); const [items, setItems] = useState<Opportunity[]>([]); const [form, setForm] = useState({ title: '', description: '', activity_type: 'volunteer_work', dimension: 'service', starts_at: '', ends_at: '', location: '', capacity: '' }); const [message, setMessage] = useState(''); const [error, setError] = useState('');
  const headers = { Authorization: `Bearer ${token}` };
  const load = async (id?: string) => { try { const memberships = await apiJson<{ id: string }[]>('communities/me', {}, token); const selected = id || communityId || memberships[0]?.id; if (!selected) throw Error('No active community selected.'); setCommunity(selected); setItems(await apiJson<Opportunity[]>(`communities/${selected}/activity-opportunities`, {}, token)); } catch (cause) { setError(cause instanceof ApiError ? cause.message : cause instanceof Error ? cause.message : 'Unable to load opportunities.'); } };
  useEffect(() => { load(); }, [token]);
  const create = async (event: React.FormEvent) => { event.preventDefault(); setError(''); setMessage(''); try { const item = await apiJson<Opportunity>(`communities/${community}/activity-opportunities`, { method: 'POST', headers: { ...headers, 'Content-Type': 'application/json' }, body: JSON.stringify({ ...form, capacity: form.capacity ? Number(form.capacity) : null, starts_at: new Date(form.starts_at).toISOString(), ends_at: new Date(form.ends_at).toISOString() }) }, token); setMessage(`Created ${item.title}.`); setForm({ title: '', description: '', activity_type: 'volunteer_work', dimension: 'service', starts_at: '', ends_at: '', location: '', capacity: '' }); await load(community); } catch (cause) { setError(cause instanceof ApiError ? cause.message : 'Unable to create opportunity.'); } };
  const publish = async (id: string) => { try { await apiJson(`activity-opportunities/${id}/publish`, { method: 'POST', headers }, token); setMessage('Opportunity published.'); await load(community); } catch (cause) { setError(cause instanceof ApiError ? cause.message : 'Unable to publish opportunity.'); } };
  return <section className="panel"><p className="eyebrow">Organization workspace</p><h2>Community opportunities</h2>{error && <p role="alert" className="error">{error}</p>}{message && <p role="status">{message}</p>}<form onSubmit={create}><label>Title<input required value={form.title} onChange={e => setForm({ ...form, title: e.target.value })} /></label><label>Description<textarea required minLength={10} value={form.description} onChange={e => setForm({ ...form, description: e.target.value })} /></label><label>Type<input required value={form.activity_type} onChange={e => setForm({ ...form, activity_type: e.target.value })} /></label><label>Starts<input required type="datetime-local" value={form.starts_at} onChange={e => setForm({ ...form, starts_at: e.target.value })} /></label><label>Ends<input required type="datetime-local" value={form.ends_at} onChange={e => setForm({ ...form, ends_at: e.target.value })} /></label><label>Location<input value={form.location} onChange={e => setForm({ ...form, location: e.target.value })} /></label><label>Capacity<input type="number" min="1" value={form.capacity} onChange={e => setForm({ ...form, capacity: e.target.value })} /></label><button>Create opportunity</button></form><div className="grid">{items.map(item => <article className="card panel" key={item.id}><h3>{item.title}</h3><p>{item.activity_type} · {item.status}</p><time>{new Date(item.starts_at).toLocaleString()}</time>{item.status === 'draft' && <button onClick={() => publish(item.id)}>Publish opportunity</button>}</article>)}</div></section>;
}
