import { useEffect, useState } from 'react';

type Member = { id: string; user_id: string; username?: string; display_name?: string; role: string; status: string };
export function OrganizerMembers({ token, communityId }: { token: string; communityId?: string }) {
  const [members, setMembers] = useState<Member[]>([]); const [error, setError] = useState(''); const [message, setMessage] = useState(''); const headers = { Authorization: `Bearer ${token}` };
  const load = async () => { let id = communityId; if (!id) { const memberships = await fetch('/api/v1/communities/me', { headers }); if (!memberships.ok) { setError('Unable to load communities.'); return; } id = (await memberships.json())[0]?.id; } if (!id) { setError('No active community selected.'); return; } const response = await fetch(`/api/v1/communities/${id}/members`, { headers }); if (!response.ok) { setError(response.status === 403 ? 'Administrator access required.' : 'Unable to load members.'); return; } setMembers((await response.json()).members); };
  useEffect(() => { load(); }, [token, communityId]);
  const updateStatus = async (member: Member, status: string) => { let id = communityId; if (!id) { const memberships = await fetch('/api/v1/communities/me', { headers }); id = (await memberships.json())[0]?.id; } const response = await fetch(`/api/v1/communities/${id}/members/${member.id}/status`, { method: 'PATCH', headers: { ...headers, 'Content-Type': 'application/json' }, body: JSON.stringify({ status }) }); if (!response.ok) { setError('Unable to update membership.'); return; } setMessage('Membership updated.'); await load(); };
  return <section className="panel"><p className="eyebrow">Community administration</p><h2>Members</h2>{error && <p role="alert" className="error">{error}</p>}{message && <p role="status">{message}</p>}{!error && !members.length && <p className="empty">No members found.</p>}<div className="stack">{members.map(member => <article className="card" key={member.id}><h3>{member.display_name || member.username || 'Private member'}</h3><p>Role: {member.role} · Status: {member.status}</p>{member.status === 'active' ? <button className="secondary" onClick={() => updateStatus(member, 'inactive')}>Deactivate</button> : <button onClick={() => updateStatus(member, 'active')}>Activate</button>}</article>)}</div></section>;
}
