import { useEffect, useState } from 'react';
import { apiJson } from './api';
import { useDraftState } from './formRecovery';
import { GovernanceConfirm } from './GovernanceConfirm';
const initial = { content_type: 'event', content_id: '', classification: 'featured', surface: 'home', starts_at: '', ends_at: '', priority: 0, is_active: false, reason: '' };
export function PromotionManager({ token }: { token: string }) {
  const [items, setItems] = useState<any[]>([]); const [candidates, setCandidates] = useState<any[]>([]); const [search, setSearch] = useState(''); const [offset, setOffset] = useState(0); const [candidateOffset, setCandidateOffset] = useState(0);
  const [editing, setEditing] = useState(''); const [seed, setSeed] = useState(initial); const draft = useDraftState(`platform:promotion:${editing || 'new'}`, seed); const form = draft.value;
  const [error, setError] = useState(''); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false); const [deactivating, setDeactivating] = useState('');
  const load = () => apiJson<any[]>(`admin/promotions?offset=${offset}`, {}, token).then(setItems).catch(e => setError(e.message));
  useEffect(() => { load(); }, [token, offset]);
  const find = async (next = 0) => { setError(''); try { setCandidates(await apiJson<any[]>(`admin/promotions/candidates?kind=${form.content_type}&q=${encodeURIComponent(search)}&offset=${next}`, {}, token)); setCandidateOffset(next); } catch(e) { setError(e instanceof Error ? e.message : 'Unable to find content'); } };
  return <section><h2>Featured / Sponsored management</h2><p>Featured is editorial. Sponsored is labelled promotion. Only eligible public-community content is selectable; task placements are additionally restricted to active community members. No checkout, authentication or attendance placements.</p>{error && <p role="alert">{error}</p>}{message && <p role="status">{message}</p>}
    <form className="panel" onSubmit={async e => { e.preventDefault(); setBusy(true); setError(''); try { await apiJson(`admin/promotions${editing ? '/' + editing : ''}`, { method: editing ? 'PUT' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...form, starts_at: new Date(form.starts_at).toISOString(), ends_at: new Date(form.ends_at).toISOString() }) }, token); await draft.clear(); setEditing(''); setSeed(initial); setMessage('Promotion saved. Delivery also checks current eligibility and schedule.'); await load(); } catch(e) { setError(e instanceof Error ? e.message : 'Unable to save promotion'); } finally { setBusy(false); } }}>
      <h3>{editing ? 'Edit placement' : 'New placement'}</h3>{draft.error && <p role="alert">{draft.error}</p>}<label>Content type<select value={form.content_type} onChange={e => { draft.set(v => ({ ...v, content_type: e.target.value, content_id: '' })); setCandidates([]); }}>{['community','event','opportunity','task'].map(v => <option key={v}>{v}</option>)}</select></label><label>Find eligible content<input value={search} onChange={e => setSearch(e.target.value)} /></label><button type="button" onClick={() => find()}>Search content</button><label>Content<select required value={form.content_id} onChange={e => draft.set(v => ({ ...v, content_id: e.target.value }))}><option value="">Select eligible content</option>{form.content_id && !candidates.some(c => c.content_id === form.content_id) && <option value={form.content_id}>Current selection ({form.content_id})</option>}{candidates.map(c => <option key={c.content_id} value={c.content_id}>{c.headline}</option>)}</select></label><button type="button" disabled={!candidateOffset} onClick={() => find(candidateOffset - 50)}>Previous matches</button><button type="button" disabled={candidates.length < 50} onClick={() => find(candidateOffset + 50)}>Next matches</button>
      <label>Classification<select value={form.classification} onChange={e => draft.set(v => ({ ...v, classification: e.target.value }))}><option value="featured">Featured</option><option value="sponsored">Sponsored</option></select></label><label>Surface<select value={form.surface} onChange={e => draft.set(v => ({ ...v, surface: e.target.value }))}>{(form.content_type === 'task' ? ['home','tasks'] : ['home','discover','event-detail','opportunities','communities','tasks']).map(v => <option key={v}>{v}</option>)}</select></label>
      <div className="form-row">{(['starts_at','ends_at'] as const).map(key => <label key={key}>{key.replace('_',' ')} (local time)<input required type="datetime-local" value={form[key]} onChange={e => draft.set(v => ({ ...v, [key]: e.target.value }))} /></label>)}</div><label>Priority (higher first)<input type="number" min={-10000} max={10000} value={form.priority} onChange={e => draft.set(v => ({ ...v, priority: Number(e.target.value) }))} /></label><label><input type="checkbox" checked={form.is_active} onChange={e => draft.set(v => ({ ...v, is_active: e.target.checked }))} />Active</label><label>Audit reason<textarea required minLength={3} maxLength={1000} value={form.reason} onChange={e => draft.set(v => ({ ...v, reason: e.target.value }))} /></label><button disabled={busy || !draft.ready}>Save placement</button>{editing && <button type="button" onClick={() => { setSeed(initial); setEditing(''); }}>Return to new placement draft</button>}</form>
    {items.map(item => <article className="card" key={item.id}><h3>{item.classification} · {item.content_type} · {item.surface}</h3><p>{item.is_active ? new Date(item.ends_at) <= new Date() ? 'Expired' : new Date(item.starts_at) > new Date() ? 'Scheduled' : 'Active (subject to content eligibility)' : 'Inactive'} · priority {item.priority}</p><p>{new Date(item.starts_at).toLocaleString()} — {new Date(item.ends_at).toLocaleString()}</p><button onClick={() => { const local = (x: string) => { const d = new Date(x); return new Date(d.getTime() - d.getTimezoneOffset() * 60000).toISOString().slice(0,16); }; setSeed({ content_type: item.content_type, content_id: item.content_id, classification: item.classification, surface: item.surface, starts_at: local(item.starts_at), ends_at: local(item.ends_at), priority: item.priority, is_active: item.is_active, reason: '' }); setEditing(item.id); }}>Edit placement</button><button disabled={!item.is_active} onClick={() => setDeactivating(item.id)}>Deactivate</button></article>)}
    <button disabled={!offset} onClick={() => setOffset(offset - 50)}>Previous placements</button><button disabled={items.length < 50} onClick={() => setOffset(offset + 50)}>Next placements</button>
    {deactivating && <GovernanceConfirm title="Deactivate promotion" consequence="The placement stops being delivered; history is retained." onClose={() => setDeactivating('')} onConfirm={async reason => { await apiJson(`admin/promotions/${deactivating}/deactivate`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ reason }) }, token); await load(); }} />}
  </section>;
}
